name: Deploy Gatsby to GitHub Pages

on:
  push:
    branches:
      - main  # Troque 'main' por 'master' ou o branch que você usa como padrão

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Certifique-se de que esta é a versão compatível com o seu projeto

      - name: Install dependencies
        run: npm ci
        
      - name: Build Gatsby site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public